/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollectionSection: typeof import('./src/components/home/CollectionSection.vue')['default']
    ConfirmationModal: typeof import('./src/components/shop/ConfirmationModal.vue')['default']
    CraftSection: typeof import('./src/components/about/CraftSection.vue')['default']
    CreativitySection: typeof import('./src/components/about/CreativitySection.vue')['default']
    DeliveryText: typeof import('./src/components/home/DeliveryText.vue')['default']
    DiscoverSection: typeof import('./src/components/about/DiscoverSection.vue')['default']
    FaceBook: typeof import('./src/components/icons/FaceBook.vue')['default']
    FAQ: typeof import('./src/components/footer/FAQ.vue')['default']
    FooterComponent: typeof import('./src/components/footer/FooterComponent.vue')['default']
    InstagramIcon: typeof import('./src/components/icons/InstagramIcon.vue')['default']
    IntroSection: typeof import('./src/components/about/IntroSection.vue')['default']
    LogoComponent: typeof import('./src/components/nav/LogoComponent.vue')['default']
    MainDetails: typeof import('./src/components/shop/MainDetails.vue')['default']
    MobileNav: typeof import('./src/components/nav/MobileNav.vue')['default']
    MobileToggle: typeof import('./src/components/nav/MobileToggle.vue')['default']
    MoonIcon: typeof import('./src/components/icons/MoonIcon.vue')['default']
    NavBar: typeof import('./src/components/nav/NavBar.vue')['default']
    ProductsList: typeof import('./src/components/shop/ProductsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunIcon: typeof import('./src/components/icons/SunIcon.vue')['default']
    TwitterIcon: typeof import('./src/components/icons/TwitterIcon.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    WhatsAPP: typeof import('./src/components/icons/WhatsAPP.vue')['default']
    WhyChooseUs: typeof import('./src/components/home/WhyChooseUs.vue')['default']
    XIcon: typeof import('./src/components/icons/XIcon.vue')['default']
  }
}
